# html lang
language: zh

# Copyright
copyright:
  ©: 1970 to 2020
#  ICP: ——备案号——

# 文章内目录
toc:
  list_number: true # true / false ；是否显示编号
  max_depth: 6 # 最大目录深度
  min_depth: 1 # 最小目录深度

# 显示发布日期与修改日期
post:
  date: true # true / false ；是否显示发布日期
  updated: true # true / false ；是否显示修改日期

# main menu navigation
menu:
  Home: /
#  About: /about
#  Contact: /contact
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/arknights.css
- https://cdn.bootcss.com/highlight.js/9.18.1/styles/atom-one-dark-reasonable.min.css

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/highlight.js/9.6.0/highlight.min.js
- /js/arknights.js
