# html lang
language: zh

# Copyright
copyright:
  ©: 1970 to 2020
#  ICP: ——备案号——

# main menu navigation
menu:
  Home: /
#  About: /about
#  Contact: /contact
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/arknights.css

# scripts loaded in the end of the body
scripts:
- /js/arknights.js
